export enum Routes {
  // public routes
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',

  // private routes
  MENU = 'MENU',

  DASHBOARD = 'DASHBOARD',
  SITES = 'SITES',
  ORDERS = 'ORDERS',
  CONTACTS = 'CONTACTS',
  PRODUCTS = 'PRODUCTS',
  REPORTS = 'REPORTS',

  SITE_SETTING = 'SITE_SETTING',
  SITE_CREATE = 'SITE_CREATE',
}
